// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2fdIF_-ItILaLevpZRhXD4AhkFVuAgg8',
    appId: '1:1056345510227:web:83dcd16f903bc0443011a6',
    messagingSenderId: '1056345510227',
    projectId: 'splitcheck-9f211',
    authDomain: 'splitcheck-9f211.firebaseapp.com',
    storageBucket: 'splitcheck-9f211.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEAoratbKv5cCD-Fc_bLr9Jq5QM2VaQ94',
    appId: '1:1056345510227:android:0f9adc8d2c309c5b3011a6',
    messagingSenderId: '1056345510227',
    projectId: 'splitcheck-9f211',
    storageBucket: 'splitcheck-9f211.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANu1QdM-wuQZcxdC54xuhtDiqbxAloXsg',
    appId: '1:1056345510227:ios:4f9ae250413e02163011a6',
    messagingSenderId: '1056345510227',
    projectId: 'splitcheck-9f211',
    storageBucket: 'splitcheck-9f211.firebasestorage.app',
    iosBundleId: 'com.example.splitcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANu1QdM-wuQZcxdC54xuhtDiqbxAloXsg',
    appId: '1:1056345510227:ios:4f9ae250413e02163011a6',
    messagingSenderId: '1056345510227',
    projectId: 'splitcheck-9f211',
    storageBucket: 'splitcheck-9f211.firebasestorage.app',
    iosBundleId: 'com.example.splitcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2fdIF_-ItILaLevpZRhXD4AhkFVuAgg8',
    appId: '1:1056345510227:web:b778b2362285cb793011a6',
    messagingSenderId: '1056345510227',
    projectId: 'splitcheck-9f211',
    authDomain: 'splitcheck-9f211.firebaseapp.com',
    storageBucket: 'splitcheck-9f211.firebasestorage.app',
  );
}
